[package]
name = "signin"
version = "0.1.0"
authors = ["Boris Faure <boris@fau.re>"]
license = "BSD-2-Clause"

[dependencies]
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
base64 = "0.4"
time = "0.1"
openssl = "0.9"
